name: example
description: A new Flutter project.

publish_to: "none"
version: 4.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_lock:
    path: ../
  local_auth: 1.1.0

flutter:
  uses-material-design: true
