name: flutter_screen_lock
description: flutter screen lock.
author: Naoki Chiba<c.nao.xx@gmail.com>
homepage: https://github.com/naoki0719/flutter_screen_lock
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
